### ISSUE TITLE
Resize is broken since 0.9.22.

### ISSUE THREAD

**Issue by ngryman** [paperjs/paper.js#662]
Hey,

On a Mac Book Pro Retina, canvas is not resized correctly, it exponentially grows until the browser tab crashes. Also canvas is zoomed (probably related to some pixel ratio stuff).

On 0.9.21, the issue is not present.

**Comment by Skalkaz** [comment]
Same problem here on win7 chrome. And I found this:
http://stackoverflow.com/questions/28896260/paper-js-wont-resize-the-canvas-correctly

**Comment by lehni** [comment]
This is probably not a bug, but due to a change in how resizing is handled. It now depends on CSS configuration to go along with the resize flag:

```css
<style type="text/css">
html,
body {
    margin: 0;
    overflow: hidden;
    height: 100%;
}

/* Scale canvas with resize attribute to full size */
canvas[resize] {
    width: 100%;
    height: 100%;
}
</style>
```
